---
cloudcore_enabled: true
cloudcore_action: deploy
cloudcore_supported_actions:
  - deploy
  - reset

cloudcore_nodeLimit: 2147483647
cloudcore_namespace: kubeedge
cloudcore_version: v1.5.0
cloudcore_devive_version: 'v1alpha2'
cloudcore_devicemodel_version: 'v1alpha2'
cloudcore_config_apiversion: 'cloudcore.config.kubeedge.io/v1alpha2'

cloudcore_cloudhub_nodePort: 30011
cloudcore_certandreadyz_nodePort: 30012
cloudcore_replicas: "1"
cloudcore_image: 'kubeedge/cloudcore:{{ cloudcore_version }}'

cloudcore_LeaderElect: '{% if cloudcore_replicas == "1" %}false{% else %}true{% endif %}'

cloudcore_advertiseAddress: '["{{ cluster_primary_ip }}"]'
