---
- name: Cloudcore
  hosts: kube-master
  become_method: sudo
  become_user: root
  become: true
  any_errors_fatal: true
  tasks:
    - import_role:
        name: cloudcore
      when:
        - cloudcore_enabled | bool
      delegate_to: localhost
      run_once: true
