---
- name: Container-runtime
  hosts: all
  become_method: sudo
  become_user: root
  become: true
  tasks:
    - import_role:
        name: docker
      when:
        - container_manager == "docker"
