---
- name: iptables-persistent
  hosts: all
  become_method: sudo
  become_user: root
  become: true
  any_errors_fatal: true
  tasks:
    - import_role:
        name: iptables-persistent
      when: iptables_persistent_enabled | bool
