{{- if .Values.fabDNS.create -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.fabDNS.name }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    {{- include "fabDNS.labels" . | nindent 4 }}
  type: ClusterIP
  ports:
    - name: dns-udp
      protocol: UDP
      port: 53
      targetPort: 53
    - name: dns-tcp
      protocol: TCP
      port: 53
      targetPort: 53
{{- end }}
