{{- if eq .Values.cluster.role "host" }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.operator.name }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    {{- include "fabedgeOperator.labels" . | nindent 4 }}
  type: NodePort
  ports:
    - protocol: TCP
      port: 3030
      targetPort: 3030
      nodePort: {{ .Values.operator.service.nodePort }}
{{- end }}
