{{- if (and .Values.fabDNS.create (eq (include "serviceHub.mode" .) "server" )) }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.serviceHub.name }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    {{- include "serviceHub.labels" . | nindent 4 }}
  type: NodePort
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: {{ .Values.serviceHub.service.nodePort }}
{{- end }}
