---
- import_tasks: register_token.yml
- import_tasks: load_image.yml

- name: Prepare directories
  file:
    path: "{{ item }}"
    state: directory
    recurse: yes
  with_items:
    - "{{ edgecore_config_directory }}"
    - "/var/lib/kubeedge"
    - "/var/lib/edged"
    - "/var/log/kubeedge"

- name: Install edgecore
  copy:
    src: edgecore-v1.5.0-x86_64
    dest: /usr/local/bin/edgecore
    mode: 0755

- name: Copy edgecore.yaml
  template:
    src: edgecore.yaml.j2
    dest: "{{ edgecore_config_directory }}/edgecore.yaml"
  notify: Enable and Restart edgecore

- name: Install edgecore.service
  template:
    src: edgecore.service.j2
    dest: "/etc/systemd/system/edgecore.service"
  notify: Enable and Restart edgecore

- meta: flush_handlers
