---
- name: Copy kubeedge-pause
  copy:
    src: kubeedge-pause-3.1-x86_64.tar
    dest: /tmp/kubeedge-pause-3.1-x86_64.tar

- name: Load kubeedge-pause
  shell: docker load -i /tmp/kubeedge-pause-3.1-x86_64.tar

- name: Copy k8s-dns-node-cache
  copy:
    src: k8s-dns-node-cache-1.16.0-x86_64.tar
    dest: /tmp/k8s-dns-node-cache-1.16.0-x86_64.tar

- name: Load k8s-dns-node-cache
  shell: docker load -i /tmp/k8s-dns-node-cache-1.16.0-x86_64.tar
