---
- name: Register token
  shell: kubectl get secret -nkubeedge tokensecret -o=jsonpath='{.data.tokendata}' | base64 -d
  environment:
      PATH: "{{ ansible_env.PATH }}:/usr/local/bin/"
  register: _edgecore_edgeHubToken
  delegate_to: "{{ groups[kubespray_master_group_name][0] }}"

- name: Set edgecore_edgeHubToken
  set_fact:
    edgecore_edgeHubToken: "{{ _edgecore_edgeHubToken.stdout_lines[0] }}"
