apiVersion: v2
name: fabedge
version: "1.0.0"
type: application
description: FabEdge is an open source edge networking solution based on kubernetes.
home: http://www.fabedge.io
sources:
  - https://github.com/FabEdge/fabedge
keywords:
  - fabedge
  - network
  - edge
maintainers:
  - name: fabedge
    email: fabedge@beyondcent.com
appVersion: "v1.0.0"
