{{- if .Values.fabDNS.create -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.fabDNS.name }}
  namespace: {{ .Release.Namespace }}
data:
  Corefile: |
    .:53 {
        errors
        health
        ready
        fabdns global {
           cluster {{ .Values.cluster.name }}
           zone {{ .Values.cluster.zone }}
           region {{ .Values.cluster.region }}
           ttl 30
        }
        cache 30
        reload
    }
{{- end }}