apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.operator.name }}
rules:
  - apiGroups:
      - fabedge.io
    resources:
      - communities
      - clusters
    verbs:
      - "*"
  - apiGroups:
      - ""
    resources:
      - nodes
      - services
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - update
  - apiGroups:
      - ""
    resources:
      - pods
      - configmaps
      - secrets
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - ""
    resources:
      - pods/status
      - configmaps/status
      - secrets/status
    verbs:
      - get
      - update
      - patch
  - apiGroups:
      - "discovery.k8s.io"
    resources:
      - endpointslices
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - crd.projectcalico.org
    resources:
      - ipamblocks
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - crd.projectcalico.org
    resources:
      - ippools
    verbs:
      - '*'
---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.operator.name }}
  namespace: {{ .Release.Namespace }}

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.operator.name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.operator.name }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.operator.name }}
    namespace: {{ .Release.Namespace }}
