name: build

on:
  release:
    types:
      - published

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
    - uses: actions/checkout@v2

    - name: package chart
      run: |
        curl -fsSL https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash -
        helm package fabedge

    - name: Uploading assets to release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          fabedge-*.tgz
          scripts/get_cluster_info.sh
          scripts/quickstart.sh
