name: release

on:
  release:
    types:
      - published

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: package chart
        run: |
          curl -fsSL https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash -
          helm package helm-chart

      - name: Uploading assets...
        uses: softprops/action-gh-release@v1
        with:
          files: |
            fabedge-*.tgz
            scripts/get_cluster_info.sh
            scripts/quickstart.sh